package com.cqupt.imis.service.model;

import java.io.Serializable;

public class Menu implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.link
     *
     * @mbg.generated
     */
    private String link;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.parents
     *
     * @mbg.generated
     */
    private Integer parents;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.childs
     *
     * @mbg.generated
     */
    private Integer childs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table menu
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.id
     *
     * @return the value of menu.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.id
     *
     * @param id the value for menu.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.name
     *
     * @return the value of menu.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.name
     *
     * @param name the value for menu.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.link
     *
     * @return the value of menu.link
     *
     * @mbg.generated
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.link
     *
     * @param link the value for menu.link
     *
     * @mbg.generated
     */
    public void setLink(String link) {
        this.link = link == null ? null : link.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.parents
     *
     * @return the value of menu.parents
     *
     * @mbg.generated
     */
    public Integer getParents() {
        return parents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.parents
     *
     * @param parents the value for menu.parents
     *
     * @mbg.generated
     */
    public void setParents(Integer parents) {
        this.parents = parents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.childs
     *
     * @return the value of menu.childs
     *
     * @mbg.generated
     */
    public Integer getChilds() {
        return childs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.childs
     *
     * @param childs the value for menu.childs
     *
     * @mbg.generated
     */
    public void setChilds(Integer childs) {
        this.childs = childs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", link=").append(link);
        sb.append(", parents=").append(parents);
        sb.append(", childs=").append(childs);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}